language: node_js

node_js:
  - '6'
  - '9'

sudo: required

before_install:
  # install cmake
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xvzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make
  - cd ..
  - cmake --version
  # install libx11 (for dlib gui)
  - apt-get install libx11-dev
  # install libpng
  - apt-get install libpng-dev

install:
  - npm install

script:
  - npm test
